### ISSUE TITLE
incompatible  for idea 2022.3 

### ISSUE THREAD

**Issue by holysky5** [lukasbach/intellij-ts-react-livetemplates#3]

**Comment by Bigismall** [comment]
Isn't just one line to change? As same as in previous commit @lukasbach?

**Comment by lukasbach** [comment]
I've updated the plugin, should be available soon once it's through Jetbrains approval process.

@Bigismall yes, it's usually just a version change. If anyone knows if it's somehow possible to publish the plugin once without having to republish every intellij update, I'd be very interested, this is a very annoying process, but to my knowledge IntelliJ does not support targeting future versions 😅 This plugin should probably never break since it's just some templates and no logic..

**Comment by Bigismall** [comment]
Damn, would be great to simply set  `untilBuild = '225.*'` - but, they cover their ass, by setting the max version to the current one. 

Thanks for updating. I believe @holysky5  and a lot of developers really appreciate your work. 
Great job Lukas!
